### ISSUE TITLE
Search input field

### ISSUE THREAD

**Issue by mmurakaru** [mmurakaru/perma-app#3]
## Value statement - a requirement, not a solution

As a **user**
I need **a SearchBox**
so that **I can search for a plant with the given scientific name, common name, synonym name etc.**

## Description (Text, Scribble, Wireframe, Design)

<img width="215" alt="Screen Shot 2020-11-16 at 10 49 35" src="https://user-images.githubusercontent.com/51744904/99238022-819fb700-27f9-11eb-9a61-cb15f6533949.png">

## Acceptance criteria

-   [x] Search input field
- [x] OnChange triggers search in the API
-   [x] Filters Plant thumbnails
- [x] PlantOverview is filtered, so if the searched plant has no plant-name it won't show

## Tasks

-   [x] Create SearchField component
-  [x] Create Service folder and API fetch file (getData.js)
-   [x] Unit-Test
-   [x] Add styling
-   [x] Add styleguidist

## Complexity

low
