### ISSUE TITLE
PlantThumbnail

### ISSUE THREAD

**Issue by mmurakaru** [mmurakaru/perma-app#5]
## Value statement - a requirement, not a solution

As a **user**
I need **a clickable thumbnail**
so that **I have a search result preview and to change into the plant detail view**

## Description (Text, Scribble, Wireframe, Design)

<img width="285" alt="Screen Shot 2020-11-16 at 00 17 31" src="https://user-images.githubusercontent.com/51744904/99199691-470a3000-27a1-11eb-8f60-2b23a7127eb6.png">

## Acceptance criteria

-   [ ] Clickable thumbnail image
-  [ ] Each thumbnail is a plant image from https://trefle.io/

## Tasks

-   [ ] Create PlantThumbnail component
-   [ ] Add image fetch/state logic
-   [ ] Add styling
-   [ ] Add styleguidist
-   [ ] Unit-Test

## Complexity

low
