### ISSUE TITLE
Combine overview + plant detail view page 

### ISSUE THREAD

**Issue by mmurakaru** [mmurakaru/perma-app#6]
## Value statement - a requirement, not a solution

As a **user**
I need **to click on a plant image**
so that **I can navigate to the plant detail view**

## Description (Text, Scribble, Wireframe, Design)

<img width="638" alt="Screen Shot 2020-11-16 at 12 40 01" src="https://user-images.githubusercontent.com/51744904/99248578-fa5a3f80-2808-11eb-891f-fe66c6263360.png">

## Acceptance criteria

-   [ ] Change from Overview page to Plant detail view when tapping on a plant thumbnail
-   [ ] Change from Plant detail view to Overview page when swiping to the bottom (motion: top to bottom)

## Tasks

- [ ] Add Router component
- [ ] Add swipe Animation
- [ ] Unit Test

## Complexity

low
