### ISSUE TITLE
Space creator

### ISSUE THREAD

**Issue by mmurakaru** [mmurakaru/perma-app#8]
## Value statement - a requirement, not a solution

As a **user**
I need **to create a space**
so that **I have a categorie that I can later add plants to**

## Description (Text, Scribble, Wireframe, Design)

<img width="516" alt="Screen Shot 2020-11-16 at 14 23 44" src="https://user-images.githubusercontent.com/51744904/99257489-6479e100-2817-11eb-9dff-246104b32628.png">

## Acceptance criteria

-   [ ] visible space Image
-   [ ] visible keyboard and focus on input field
-   [ ] visible button to confirm and create a space

## Tasks

- [ ] Create SpaceCreate component
- [ ] Unit-test 
- [ ] Add styling
- [ ] Add styleguidist

## Complexity

low
